calculation/urls.py
from django.urls import path
from . import views


app_name = 'calculation'
urlpatterns = [
    # path('', views.calculate_mean, name='index'),
    path('', views.calculate_mean, name='index'),
    path('reset_session', views.reset_session, name='reset_session')

]

meanproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('calculation.urls')),
    path('admin/', admin.site.urls),
]

calculation/models.py
# Create your models here.

calculation/forms.py
from django import forms
 
class CalculateForm(forms.Form):

    ## validates input: input has to be either a list of int or an int ##
    def validate_type(value):
        if(isinstance(value,int) or (isinstance(value,list)  and all([isinstance(item, int) for item in value]))):
            pass
        else:
            
            raise forms.ValidationError(code='invalid_type',
            message='Input type is invalid. Accepted values are single numbers or a list of numbers. Example: [1,5,6].')

    input_numbers= forms.JSONField(label='',required=True, initial=list,validators=[validate_type])

calculation/views.py
from statistics import mean
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from .forms import CalculateForm

## calculates mean out of the input_numbers and stores it in the session and sends feedback to the user (success and error messages). ##

def calculate_mean(request):
    if request.method == 'POST':
        form = CalculateForm(request.POST)
        if form.is_valid():
            input_numbers = form.cleaned_data['input_numbers']
            ## if input is only one number convert it to list
            if(isinstance(input_numbers,int)):
                input_numbers=[input_numbers]

            ##init average if no value is stored in cash
            if(request.session.get('average','First Calcualtion')=='First Calcualtion'):
                request.session['input_numbers']=input_numbers
                request.session['average'] = mean(input_numbers)
            else:            
                new_numbers=input_numbers
                old_numbers=request.session['input_numbers']
                request.session['input_numbers']=old_numbers+new_numbers
                request.session['average'] = mean(new_numbers+old_numbers)
            output = {
                'type': 'success'
                }
            messages.success(request, JsonResponse(output).content)

        else:
            messages.error(request, JsonResponse(form.errors, status=400).content)
    else:
        form = CalculateForm()
    return render(request, 'calculation/index.html', {'form': form})


## reset stored mean value ##

def reset_session(request):
    try:
        del request.session['average']
        del request.session['input_numbers']
    except KeyError:
         pass
    messages.success(request, "Value reset is done.")

    return HttpResponseRedirect(reverse('calculation:index'))

calculation/templates/calculation/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Calculate Mean</title>
  </head>
    <body class="bg-light">
        <div class="bg-white container">
    
          <div class="jumbotron">
            <h1 class="display-4">Calculate Mean:</h1>
            {% include 'messages.html' %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.input_numbers }}
                </div>
                <input class="btn btn-outline-primary" type="submit" value="Caclulate">
                <button class="btn btn-outline-info" type="button" data-toggle="collapse" data-target="#collapseMean" aria-expanded="false" aria-controls="collapseMean">
                    Current Mean
                </button>
                <a class="btn btn-outline-warning" href="{% url 'calculation:reset_session' %}">Reset The Internal State</a>

            </form>


            <div class="collapse" id="collapseMean">
                <div class="card bg-light mb-3 card-body">
                    {{ request.session.average }}
                </div>
            </div>

            
          </div>
             
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 


</body>
</html>

calculation/templates/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    <strong>{{ message|escape }}</strong>
  </div>
</div>
{% endfor %}